upstream fastapi_app {
    server app:8000;
}

# HTTP: только challenge + редирект на https
server {
    listen 80;
    listen [::]:80;

    server_name predpacks.com www.predpacks.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS: основной сервер
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name predpacks.com www.predpacks.com;

    ssl_certificate     /etc/letsencrypt/live/predpacks.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/predpacks.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/predpacks.com/chain.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass         http://fastapi_app;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
    }
}